### ISSUE TITLE
Gitter IM 

### ISSUE THREAD

**Issue by Jaikant** [ReactBangalore/reactbangalore.github.io#4]
Created a gitter room for React Bangalore, can it be integrated to this repo.

https://gitter.im/React-Bangalore/Lobby

**Comment by siddharthkp** [comment]
Nice! What's the popular form of chat in the group? 

Is it slack, gitter, hipchat, etc?

**Comment by akiran** [comment]
Actually we already have a discord channel.  
https://discord.gg/dhD8vyQ

I am not promoting it recently because it is not very active.
We can give it one more try

**Comment by Jaikant** [comment]
@siddharthkp slack is good for teams within organisations. For open source slack is not great.
@akiran Haven't used discord earlier, we can try it. 
gitter works great because it gives the feel of a chat communication, though it takes time to get into that kind of mode. Maybe it is too early for that.

**Comment by Jaikant** [comment]
Btw, gitter has some cool github integrations, you can see all the activity happening on github on the side panel, who starred the repo, who commented and what not :)

**Comment by akiran** [comment]
Reactiflux, biggest react group is using discordapp.
https://www.reactiflux.com/

So we went discord way back them

**Comment by siddharthkp** [comment]
>  slack is good for teams within organisations. For open source slack is not great.

Not so sure about that.

I'm biased towards slack because a lot of people* use it at work, and a lot of great OSS communities are moving to it now.

Let the community decide 😄 @akiran Poll on the react bangalore twitter?


* citation required 😛

**Comment by akiran** [comment]
@siddharthkp Slack free account has some limitations like 10k messages etc.
But as you said, I think it is the easy for many users to use slack.

Lets start with slack to reduce the initial barrier. 
When we hit the limits of free account, we might think of other solutions

**Comment by akiran** [comment]
@siddharthkp @Jaikant I created this auto invite link 
https://reactbangalore.herokuapp.com/
